'use client';
import {useEffect,useRef,useState} from 'react';
import type {PortfolioProject,ProjectPhoto} from '../data/projects';
import {asset} from '../lib/urls';
function Photograph({photo,index,eager,onOpen}:{photo:ProjectPhoto;index:number;eager?:boolean;onOpen:()=>void}){
 return <figure className={`journal-photo photo-${photo.size}`} data-photo-reveal><button className="photo-frame" onClick={onOpen} aria-label={`사진 크게 보기: ${photo.caption}`}><img className="moving-photo" src={asset(photo.file)} srcSet={`${asset(photo.file.replace('.webp','-small.webp'))} 768w, ${asset(photo.file)} 1536w`} sizes={photo.size==='wide'?'92vw':'(max-width:600px) 90vw,45vw'} alt={photo.caption} width={photo.size==='medium'?1024:1536} height={photo.size==='medium'?1536:1024} loading={eager?'eager':'lazy'} fetchPriority={eager?'high':'auto'}/><span className="photo-open" aria-hidden="true">VIEW +</span></button><figcaption><span>0{index+1} /</span><span>{photo.caption}</span></figcaption></figure>;
}
export default function ProjectExperience({project}:{project:PortfolioProject}){
 const root=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null);const [active,setActive]=useState<number|null>(null);
 useEffect(()=>{
  const el=root.current;if(!el||new URLSearchParams(location.search).has('agency-editor')||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  el.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){(entry.target as HTMLElement).dataset.visible='true';observer.unobserve(entry.target);}}),{threshold:.06,rootMargin:'0px 0px -20px 0px'});el.querySelectorAll('[data-photo-reveal]').forEach(photo=>observer.observe(photo));let frame=0;
  const update=()=>{frame=0;const bounds=el.getBoundingClientRect();el.style.setProperty('--reading-progress',String(Math.max(0,Math.min(1,(-bounds.top+innerHeight*.2)/Math.max(1,bounds.height-innerHeight*.8)))));el.querySelectorAll<HTMLElement>('.photo-frame').forEach(photo=>{const rect=photo.getBoundingClientRect();if(rect.bottom<0||rect.top>innerHeight)return;photo.style.setProperty('--photo-offset',`${Math.max(-16,Math.min(16,(innerHeight*.5-rect.top-rect.height*.5)*.028)).toFixed(2)}px`);});};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update);};addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);update();return()=>{observer.disconnect();removeEventListener('scroll',scroll);removeEventListener('resize',scroll);cancelAnimationFrame(frame);el.classList.remove('motion-ready');};
 },[]);
 useEffect(()=>{const viewer=dialog.current;if(!viewer)return;if(active===null){if(viewer.open)viewer.close();return;}if(!viewer.open)viewer.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[active]);
 const open=(index:number)=>{if(!new URLSearchParams(location.search).has('agency-editor'))setActive(index);};const step=(direction:number)=>setActive(value=>value===null?null:(value+direction+project.gallery.length)%project.gallery.length);const current=active===null?null:project.gallery[active];
 return <div className="project-experience" ref={root}><div className="reading-progress" aria-hidden="true"/><div className="journal-hero"><Photograph photo={project.gallery[0]} index={0} eager onOpen={()=>open(0)}/></div><section className="journal-introduction" data-photo-reveal><div><span className="eyebrow">THE DESIGN INTENT</span><h2>{project.story[0].title}</h2></div><div><p>{project.text}</p><p>{project.story[0].text}</p></div></section><div className="journal-wide"><Photograph photo={project.gallery[1]} index={1} onOpen={()=>open(1)}/></div><div className="journal-pair"><Photograph photo={project.gallery[2]} index={2} onOpen={()=>open(2)}/><Photograph photo={project.gallery[3]} index={3} onOpen={()=>open(3)}/></div><section className="journal-quote" data-photo-reveal><span className="eyebrow">SPACE, IN ITS OWN RHYTHM</span><h2>{project.story[1].title}</h2><p>{project.story[1].text}</p></section><div className="journal-details"><Photograph photo={project.gallery[4]} index={4} onOpen={()=>open(4)}/><div className="detail-note" data-photo-reveal><span className="eyebrow">A CLOSER LOOK</span><h3>디테일이 만드는<br/>공간의 온도.</h3><p>{project.materials}</p><div className="project-palette" aria-label="프로젝트 색상">{project.palette.map(color=><span key={color} style={{background:color}} title={color}/>)}</div></div><Photograph photo={project.gallery[5]} index={5} onOpen={()=>open(5)}/></div><section className="journal-summary" data-photo-reveal><span className="eyebrow">DESIGN NOTES / {project.en}</span><ul>{project.details.map(item=><li key={item}>{item}</li>)}</ul><p>가상 프로젝트 · AI 제작 이미지 · 실제 시공 실적이 아닙니다.</p></section><dialog ref={dialog} className="photo-viewer" aria-label={`${project.title} 사진 뷰어`} onCancel={()=>setActive(null)} onClose={()=>setActive(null)} onClick={event=>{if(event.target===event.currentTarget)setActive(null);}} onKeyDown={event=>{if(event.key==='ArrowRight'){event.preventDefault();step(1);}if(event.key==='ArrowLeft'){event.preventDefault();step(-1);}}}><button className="viewer-close" autoFocus onClick={()=>setActive(null)} aria-label="사진 뷰어 닫기">닫기 ×</button>{current&&<><img src={asset(current.file)} alt={current.caption}/><div className="viewer-footer"><button onClick={()=>step(-1)} aria-label="이전 사진">←</button><div><span>{String((active??0)+1).padStart(2,'0')} / 06</span><p>{current.caption}</p></div><button onClick={()=>step(1)} aria-label="다음 사진">→</button></div></>}</dialog></div>;
}
