import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {chromium} from 'playwright';
const app=path.resolve('templates/food-cafe/oven-note/out'),prefix='/agency-web-templates/food-cafe/oven-note';
const mime={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.json':'application/json','.webp':'image/webp','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{const route=new URL(req.url,'http://x').pathname;if(!route.startsWith(prefix+'/'))return res.writeHead(404).end();const relative=decodeURIComponent(route.slice(prefix.length+1));const file=path.resolve(app,relative,(!relative||relative.endsWith('/'))?'index.html':'');if(!file.startsWith(app+path.sep)||!fs.existsSync(file))return res.writeHead(404).end();res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome'});const context=await browser.newContext({viewport:{width:1440,height:900},permissions:['clipboard-read','clipboard-write'],reducedMotion:'reduce'});const page=await context.newPage();const errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)missing.push(r.url());});const url=process.env.BAKERY_URL||`http://127.0.0.1:${server.address().port}${prefix}`;fs.mkdirSync('../bakery-qa',{recursive:true});
try{const routes=['/','/menu/','/bakery/','/journal/','/visit/','/privacy/','/journal/layers/','/journal/a-small-pause/','/journal/take-a-little-home/'];const titles=new Set();for(const route of routes){await page.goto(url+route,{waitUntil:'networkidle'});titles.add(await page.title());assert.equal(await page.locator('h1').count(),1);assert.ok((await page.locator('meta[name=robots]').getAttribute('content')).includes('noindex'));assert.ok((await page.locator('link[rel=canonical]').getAttribute('href')).endsWith(prefix+route));await page.locator('img').evaluateAll(images=>images.forEach(i=>i.loading='eager'));for(const img of await page.locator('img').all())await img.evaluate(i=>i.decode());for(const width of [360,768,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' overflow '+width);}}assert.equal(titles.size,9);
await page.goto(url+'/menu/',{waitUntil:'networkidle'});assert.equal(await page.locator('.product').count(),7);await page.getByRole('button',{name:'달콤한 것',exact:true}).click();assert.equal(await page.locator('.product').count(),2);await page.locator('.product').first().click();assert.equal(await page.locator('dialog').evaluate(d=>d.open),true);assert.equal(await page.getByRole('dialog',{name:'시나몬 스월'}).count(),1);assert.ok((await page.locator('dialog').innerText()).includes('알레르기'));await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').evaluate(d=>d.open),false);await page.getByRole('button',{name:'마실 것',exact:true}).click();assert.equal(await page.locator('.product').count(),2);
await page.goto(url+'/',{waitUntil:'networkidle'});await page.getByRole('button',{name:/14:00/}).click();assert.ok((await page.locator('.clock-content').innerText()).includes('레몬'));await page.getByLabel('빵 한 조각').selectOption('lemon');await page.getByLabel('마실 것 한 잔').selectOption('citrus-tea');assert.ok((await page.locator('.receipt-total').innerText()).includes('10,700'));await page.getByRole('button',{name:/조합 메모 복사/}).click();await page.waitForFunction(()=>document.querySelector('.copy-status').textContent.includes('복사했습니다'));assert.ok((await page.evaluate(()=>navigator.clipboard.readText())).includes('레몬 버터 케이크'));await page.evaluate(()=>scrollTo(0,1000));assert.equal(await page.locator('.site-header').evaluate(e=>Math.round(e.getBoundingClientRect().top)),0);
await page.evaluate(()=>scrollTo(0,0));await page.locator('img').evaluateAll(images=>images.forEach(i=>i.loading='eager'));for(const img of await page.locator('img').all())await img.evaluate(i=>i.decode());await page.screenshot({path:'../bakery-qa/home-desktop.png',fullPage:true});await page.screenshot({path:'agency/assets/images/portfolio/food-oven-note.jpg',type:'jpeg',quality:88});await page.setViewportSize({width:360,height:800});await page.screenshot({path:'../bakery-qa/home-mobile.png',fullPage:true});
await page.setViewportSize({width:1440,height:900});await page.goto(url+'/editor/',{waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelector('#status')&&!document.querySelector('#status').textContent.includes('불러오는'));const frame=page.frames().find(f=>f.url().includes('agency-editor=1'));assert.ok(frame);await frame.locator('h1').waitFor();const target=await frame.locator('h1').evaluate(el=>({key:el.dataset.agencyKey,section:el.closest('section').dataset.agencyKey}));assert.ok(target.key);await page.locator('#sections').selectOption(target.section);let current=target.section;for(const segment of target.key.split(' > ').slice(current.split(' > ').length)){current+=' > '+segment;await page.locator('#children').selectOption(current);}await page.locator('[data-tab=content]').click();await page.locator('#contentForm .field-input').fill('빵 에디터 저장 검증');await page.waitForTimeout(200);assert.equal(await frame.locator('h1').innerText(),'빵 에디터 저장 검증');await page.locator('#save').click();await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(500);const saved=page.frames().find(f=>f.url().includes('agency-editor=1'));assert.equal(await saved.locator('h1').innerText(),'빵 에디터 저장 검증');assert.equal((await page.locator('#pages option').count())>=9,true);
assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('PASS: 9 routes, metadata, photos, 360/768/1440 overflow, menu filter/dialog/Escape, time tabs, pairing/copy, sticky header, editor save/reload.');
}finally{await browser.close();await new Promise(r=>server.close(r));}


