import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {chromium} from 'playwright';
const base='/agency-web-templates/biz-manufacturing/fieldmap',root=path.resolve('templates/biz-manufacturing/fieldmap/out');
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local');let rel=decodeURIComponent(url.pathname.slice(base.length));if(url.pathname.endsWith('/'))rel+='index.html';const file=path.resolve(root,'.'+rel);if(!url.pathname.startsWith(base+'/')||!file.startsWith(root+path.sep)||!fs.existsSync(file))return res.writeHead(404).end();const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.woff2':'font/woff2','.json':'application/json'};res.writeHead(200,{'Content-Type':type[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=process.env.FIELDMAP_ORIGIN||`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({channel:'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));fs.mkdirSync('../fieldmap-qa',{recursive:true});
const ids=['SH-120','CP-200','RX-4040','LR-15','HB-310','OT-500','BK-07','SM-3'];
try{
 for(const route of ['','products/','capability/','applications/ev/',...ids.map(id=>'products/'+id+'/')]){
  await page.goto(origin+base+'/'+route);await page.locator('h1').waitFor();
  for(const image of await page.locator('.product-photo').all()){await image.scrollIntoViewIfNeeded();await image.evaluate(el=>el.decode());assert.ok(await image.getAttribute('alt'));}
  for(const width of [360,768,1440]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),route+' overflow '+width)}
  if(route.startsWith('products/')&&ids.some(id=>route==='products/'+id+'/'))assert.ok((await page.locator('.detail-fig img').getAttribute('src')).includes(route.split('/')[1].toLowerCase()+'.webp'));
 }
 await page.goto(origin+base+'/products/');assert.equal(await page.locator('.prod').count(),8);assert.equal(new Set(await page.locator('.prod img').evaluateAll(nodes=>nodes.map(n=>n.src))).size,8);
 await page.getByRole('button',{name:'전기차 배터리',exact:false}).click();assert.equal(await page.locator('.prod').count(),2);await page.locator('.cats').getByRole('button',{name:'방열판',exact:true}).click();assert.equal(await page.locator('.prod').count(),1);await page.locator('.prod .add').click();await page.goto(origin+base+'/quote/');assert.ok((await page.locator('.picked').textContent()).includes('CP-200'));await page.getByRole('button',{name:'보낼 내용 정리하기'}).click();assert.ok((await page.locator('.out pre').textContent()).includes('CP-200'));
 await page.goto(origin+base+'/capability/');await page.locator('.motion-screen').scrollIntoViewIfNeeded();await page.waitForTimeout(300);assert.equal(await page.locator('.motion-play').getAttribute('aria-pressed'),'false');
 for(let step=0;step<6;step++){await page.locator('.motion-stages button').nth(step).click();assert.equal(await page.locator('.motion-screen').getAttribute('data-stage'),String(step));assert.equal(await page.locator('.motion-stages button').nth(step).getAttribute('aria-pressed'),'true');assert.ok(await page.locator('.motion-screen svg').getAttribute('aria-label'));}
 await page.locator('.motion-stages button').nth(3).click();await page.locator('.manufacturing').screenshot({path:'../fieldmap-qa/motion.jpg'});await page.screenshot({path:'../fieldmap-qa/process.jpg',fullPage:true});
 await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('.motion-stages button').first().click();await page.getByRole('button',{name:'모션 재생',exact:true}).click();await page.waitForTimeout(4000);assert.notEqual(await page.locator('.motion-screen').getAttribute('data-stage'),'0');await page.getByRole('button',{name:'모션 일시정지',exact:true}).click();const stage=await page.locator('.motion-screen').getAttribute('data-stage');await page.waitForTimeout(3900);assert.equal(await page.locator('.motion-screen').getAttribute('data-stage'),stage);
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto(origin+base+'/editor/');await page.locator('iframe').waitFor();await page.waitForFunction(()=>document.querySelectorAll('#pages option').length>8);
 await page.evaluate(()=>localStorage.clear());await page.goto(origin+base+'/');for(const img of await page.locator('.product-photo').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(el=>el.decode());}await page.evaluate(()=>scrollTo(0,0));assert.equal(await page.locator('.manufacturing').count(),1);await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'../fieldmap-qa/home.jpg',fullPage:true});await page.screenshot({path:'agency/assets/images/portfolio/manufacturing-fieldmap.jpg'});await page.setViewportSize({width:360,height:900});await page.screenshot({path:'../fieldmap-qa/mobile.jpg',fullPage:true});assert.deepEqual(errors,[]);
 console.log('PASS: eight distinct product images/details, filters and quote persistence, responsive layouts, six motion stages, auto playback/pause/reduced motion and editor.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
