const {chromium}=require('playwright');
const http=require('http'),fs=require('fs'),path=require('path');
const prefix='/agency-web-templates/biz-manufacturing/isoline';
const root=path.resolve('templates/biz-manufacturing/isoline/out');
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.svg':'image/svg+xml','.json':'application/json','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(!p.startsWith(prefix)){res.writeHead(404);return res.end();}p=p.slice(prefix.length)||'/';let f=path.join(root,p);if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',types[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(4173,r));const browser=await chromium.launch({headless:true,channel:'msedge'});const errors=[];const page=await browser.newPage();page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(10000);page.on('pageerror',e=>errors.push(e.message));let base=process.env.QA_URL||`http://localhost:4173${prefix}`;
for(const width of [360,768,1440]){await page.setViewportSize({width,height:1000});await page.goto(base+'/');await page.waitForTimeout(700);await page.locator('img').evaluateAll(els=>Promise.all(els.map(e=>{e.loading="eager";return e.decode()})));const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Overflow '+width);await page.screenshot({path:`../isoline-${width}.png`,fullPage:true});}
await page.getByRole('button',{name:'자동 모션 정지'}).click();await page.getByRole('button',{name:'조립해 보기'}).click();if(await page.locator('.explode').evaluate(e=>e.classList.contains('open')))throw Error('assembly failed');await page.getByRole('button',{name:'분해해 보기'}).click();
for(const route of ['/parts/','/fields/','/about/','/process/','/rfq/',...['SH-120','CP-200','RX-4040','LR-15','HB-310','OT-500','BK-07','SM-3'].map(x=>'/parts/'+x+'/')]){await page.goto(base+route);await page.locator('img').evaluateAll(els=>Promise.all(els.map(e=>{e.loading="eager";return e.decode()})));if(await page.locator('h1').count()!==1)throw Error(route+' h1');if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error(route+' overflow');}
await page.goto(base+'/parts/');
if(await page.locator('#main-menu [aria-current="page"]').textContent()!=='제품 카탈로그')throw Error('active menu');
if(await page.locator('.catalog-grid li').count()!==8)throw Error('catalog total');
await page.getByLabel('제품 검색',{exact:true}).fill('A7075');if(await page.locator('.catalog-grid li').count()!==1)throw Error('material search');
await page.getByLabel('제품 검색',{exact:true}).fill('no-such-part');await page.getByRole('heading',{name:'조건에 맞는 제품이 없습니다.'}).waitFor();await page.getByRole('button',{name:'전체 제품 보기'}).click();
await page.getByRole('button',{name:'방열판',exact:true}).click();if(await page.locator('.catalog-grid li').count()!==2)throw Error('category filter');
await page.getByRole('button',{name:'하우징·케이스',exact:true}).click();await page.goBack();await page.waitForTimeout(200);if(await page.getByRole('button',{name:'방열판',exact:true}).getAttribute('aria-pressed')!=='true')throw Error('history category');
await page.getByLabel('적용 분야',{exact:true}).selectOption('semi');if(await page.locator('.catalog-grid li').count()!==1)throw Error('combined filter');
await page.goto(base+'/parts/BK-07/');await page.getByRole('link',{name:'이 제품으로 견적 준비 →'}).click();await page.getByRole('checkbox',{name:/로봇 관절 브래킷/}).waitFor();if(!await page.getByRole('checkbox',{name:/로봇 관절 브래킷/}).isChecked())throw Error('product prefill');
await page.getByLabel('BK-07',{exact:true}).fill('10개');await page.getByRole('radio',{name:'전기차 배터리',exact:true}).check();if(!await page.getByRole('checkbox',{name:/로봇 관절 브래킷/}).isChecked())throw Error('selection lost');
await page.locator('input[type=date]').fill('2026-12-01');await page.getByRole('radio',{name:'양산 검토',exact:true}).check();await page.getByLabel('추가 요청',{exact:true}).fill('검사 성적서 요청');
const memo=await page.getByLabel('견적 준비 메모',{exact:true}).inputValue();if(!memo.includes('10개')||!memo.includes('2026-12-01')||!memo.includes('검사 성적서 요청'))throw Error('memo missing inputs');
await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.getByRole('button',{name:'메모 복사',exact:true}).click();await page.getByText('견적 준비 메모를 복사했습니다.',{exact:true}).waitFor();if((await page.evaluate(()=>navigator.clipboard.readText())).replace(/\r\n/g,'\n')!==memo)throw Error('clipboard mismatch');
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'텍스트 파일 저장'}).click();const download=await downloadPromise;const file=await download.path();if(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,'')!==memo)throw Error('download content');
await page.getByRole('button',{name:'작성 초기화'}).click();if(await page.getByRole('checkbox',{checked:true}).count())throw Error('reset');
await page.goto(base+'/fields/#led');await page.waitForTimeout(200);if(await page.getByRole('button',{name:'LED 조명',exact:true}).getAttribute('aria-pressed')!=='true')throw Error('field direct link');await page.getByRole('button',{name:'의료기기',exact:true}).click();await page.goBack();await page.waitForTimeout(200);if(await page.getByRole('button',{name:'LED 조명',exact:true}).getAttribute('aria-pressed')!=='true')throw Error('field history');
for(const route of ['/parts/','/rfq/?part=RX-4040']){await page.setViewportSize({width:360,height:900});await page.goto(base+route);await page.waitForTimeout(200);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('mobile controls overflow');await page.screenshot({path:'../isoline-'+(route.includes('rfq')?'rfq':'catalog')+'-360.png',fullPage:true});}
await page.getByRole('button',{name:'메뉴 열기'}).click();await page.locator('#main-menu').getByRole('link',{name:'제품 카탈로그'}).click();await page.getByRole('heading',{name:'설계에 맞는 부품 찾기'}).waitFor();if(await page.getByRole('button',{name:'메뉴 열기'}).getAttribute('aria-expanded')!=='false')throw Error('mobile menu remains open');
console.log('Functional checks passed; editor next');await page.waitForTimeout(300);await page.goto(base+'/editor/');await page.waitForTimeout(800);if(await page.locator('iframe').count()===0)throw Error('editor iframe missing');
if(errors.length)throw Error(errors.join('\n'));console.log('PASS: 14 pages, images, responsive navigation, catalog search/filter/history, RFQ prefill/quantity/clipboard/download/reset, field history, editor.');await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});
