import { BASE_PATH } from "@/lib/config";
import Link from "next/link"; import Image from "next/image"; import {site} from "@/data/site"; import CountUp from "@/components/CountUp"; import ServiceExplorer from "@/components/ServiceExplorer"; import CaseSlider from "@/components/CaseSlider";
export default function Home(){return <>
<section className="heroNew"><Image src={`${BASE_PATH}/images/hero-handshake.webp`} alt="상담을 마치고 악수하는 노무사와 의뢰인" fill priority sizes="100vw"/><div className="heroShade"/><div className="heroNewCopy"><p className="eyebrow">LABOR STRATEGY · GWANGJU</p><h1>일의 갈등을,<br/><em>합의 가능한 다음 단계</em>로.</h1><p>해고·임금·산재·인사 문제. 감정이 앞선 순간에도 기한, 근거, 선택지는 분명해야 합니다.</p><div className="actions"><Link className="btn primary" href="/contact">내 상황 먼저 정리하기</Link><Link className="btn glass" href="/cases">해결 사례 보기</Link></div></div><div className="heroTicker"><span>기한을 놓치지 않게</span><span>자료를 흩어지지 않게</span><span>선택을 어렵지 않게</span></div></section>
<section className="metrics" aria-label="주요 상담 기준"><CountUp value={3} suffix="개월" label="부당해고 구제신청 기한"/><CountUp value={3} suffix="년" label="임금채권 시효 확인"/><CountUp value={4} suffix="단계" label="상담부터 진행까지"/><CountUp value={365} suffix="일" label="언제든 상담 메모 준비"/></section>
<section className="section introEditorial"><div><p className="eyebrow">WHAT WE DO</p><h2>설명보다 먼저,<br/>판단의 기준을 세웁니다.</h2></div><div><p className="bigCopy">사건 이름부터 정하지 않습니다. 지금 가장 급한 날짜, 남아 있는 자료, 원하는 결과부터 확인합니다.</p><div className="principles"><span>01 · 기한</span><span>02 · 증거</span><span>03 · 선택지</span></div></div></section>
<section className="section practice"><div className="sectionHead compact"><div><p className="eyebrow">PRACTICE AREAS</p><h2>업무를 선택하면<br/>진행 방식이 보입니다.</h2></div><p>카드를 눌러 주요 쟁점과 준비자료를 확인하세요.</p></div><ServiceExplorer/></section>
<section className="imageStatement"><Image src={`${BASE_PATH}/images/negotiation.webp`} alt="회의실에서 노무 현안을 협의하는 모습" fill sizes="100vw"/><div/><blockquote>“맞서는 주장 사이에서,<br/>움직일 수 있는 합의점을 찾습니다.”</blockquote></section>
<section className="section caseSection"><div className="sectionHead compact"><div><p className="eyebrow">SELECTED CASES</p><h2>결과보다,<br/>해결의 과정을 봅니다.</h2></div><p>개별 사례는 이해를 돕기 위해 비식별·재구성한 포트폴리오용 예시입니다.</p></div><CaseSlider/></section>
<section className="splitPromise"><div className="promiseImage"><Image src={`${BASE_PATH}/images/resolution.webp`} alt="상담 결과를 함께 확인하는 의뢰인과 노무사" fill sizes="(max-width: 900px) 100vw, 50vw"/></div><div className="promiseCopy"><p className="eyebrow">OUR PROMISE</p><h2>결론만 전하지 않습니다.<br/>왜 그런지, 다음은 무엇인지까지.</h2><ul><li><b>01</b><span>가능한 결과와 어려운 지점을 함께 설명합니다.</span></li><li><b>02</b><span>업무 범위와 비용은 시작 전에 명확히 안내합니다.</span></li><li><b>03</b><span>진행 상황과 다음 일정을 단계마다 공유합니다.</span></li></ul></div></section>
<section className="cta premiumCta"><div><p className="eyebrow">READY TO TALK</p><h2>첫 상담은 사건을 맡기는 자리가 아니라,<br/>방향을 확인하는 자리입니다.</h2><p>{site.hours} · {site.tel}</p></div><Link className="btn primary" href="/contact">상담 준비 시작</Link></section>
</>}
