import Link from "next/link"; import { services,site,steps } from "@/data/site";
export default function Home(){return <>
<section className="hero"><div className="heroCopy"><p className="eyebrow">ISSUE MANAGEMENT FOR WORK</p><h1>문제보다 먼저,<br/><em>기한</em>을 봅니다.</h1><p>해고, 임금, 산재, 인사 이슈. 일이 복잡해질수록 중요한 사실과 기한부터 분명하게 정리합니다.</p><div className="actions"><Link className="btn primary" href="/contact">상담 준비하기</Link><Link className="btn ghost" href="/services">업무영역 보기</Link></div></div><div className="deadline" aria-label="주요 상담 기준"><div><span>부당해고 구제</span><b>3M</b><small>신청 기한 유의</small></div><div><span>임금채권 시효</span><b>3Y</b><small>사안별 확인 필요</small></div><div><span>첫 상담 단계</span><b>01</b><small>사실과 날짜 정리</small></div><div><span>상담 준비 항목</span><b>04</b><small>당사자·일시·자료·질문</small></div></div></section>
<section className="audience section"><div className="sectionHead"><div><p className="eyebrow">START FROM YOUR SIDE</p><h2>같은 일도,<br/>확인할 순서는 다릅니다.</h2></div><p>지금의 위치를 선택하면 먼저 살펴볼 업무와 상담 준비 항목을 빠르게 확인할 수 있습니다.</p></div><div className="audienceGrid"><Link href="/services#employer"><span>FOR EMPLOYER</span><b>사업주·인사담당자</b><p>근로계약, 취업규칙, 징계, 임금체계와 일상적인 노무관리 기준을 점검합니다.</p><strong>회사 업무 보기</strong></Link><Link href="/services#worker"><span>FOR WORKER</span><b>근로자·퇴직자</b><p>임금체불, 부당해고, 산업재해처럼 기한과 자료가 중요한 문제부터 정리합니다.</p><strong>개인 사건 보기</strong></Link></div></section>
<section className="section services"><div className="sectionHead"><div><p className="eyebrow">WORKBOARD 01</p><h2>일의 문제를<br/>업무 단위로 정리합니다.</h2></div><p>상담 전에는 사건명을 정하기보다 지금 가장 급한 일과 남은 기한을 확인하는 것이 먼저입니다.</p></div><div className="serviceGrid">{services.slice(0,4).map(s=><article key={s.no}><div className="cardTop"><span>{s.type}</span><b>{s.no}</b></div><h3>{s.title}</h3><p>{s.desc}</p><mark>{s.tag}</mark></article>)}</div><Link className="textLink" href="/services">전체 업무영역 →</Link></section>
<section className="statement"><p>OUR POINT OF VIEW</p><h2>법을 나열하는 상담보다,<br/><em>다음 행동이 보이는 설명</em>을 합니다.</h2><div><span>기한</span><span>근거</span><span>선택지</span></div></section>
<section className="dark section"><p className="eyebrow">HOW WE WORK</p><h2>서두르되, 순서를 지킵니다.</h2><div className="stepGrid">{steps.slice(0,3).map(s=><article key={s[0]}><b>{s[0]}</b><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div><Link className="btn mint" href="/process">상담 절차 확인</Link></section>
<section className="section issueCheck"><div><p className="eyebrow">FIRST CHECK</p><h2>상담 전에<br/>네 가지만 메모하세요.</h2></div><ol><li><b>당사자</b><span>누구에게 생긴 일인가요?</span></li><li><b>날짜</b><span>처음과 최근의 날짜는 언제인가요?</span></li><li><b>자료</b><span>계약서와 통지서를 가지고 있나요?</span></li><li><b>질문</b><span>가장 먼저 알고 싶은 것은 무엇인가요?</span></li></ol></section>
<section className="section resourcePreview"><div><p className="eyebrow">LABOR NOTES</p><h2>읽고 끝나는 자료가 아니라,<br/>확인하고 준비하는 자료.</h2></div><div className="resourceLinks"><Link href="/resources#update"><span>01 · 법·제도 업데이트</span><b>바뀐 기준을 짧고 정확하게</b></Link><Link href="/resources#check"><span>02 · 실무 체크리스트</span><b>사업장에서 바로 확인할 항목</b></Link><Link href="/resources#case"><span>03 · 사건 준비 노트</span><b>상담 전 모아야 할 날짜와 자료</b></Link></div></section>
<section className="consultOptions"><div><p className="eyebrow">CHOOSE HOW TO TALK</p><h2>상담 방식부터<br/>편하게 선택하세요.</h2></div><div className="optionGrid"><article><b>01</b><h3>전화 상담</h3><p>급한 기한과 상담 가능 여부를 먼저 확인합니다.</p></article><article><b>02</b><h3>방문 상담</h3><p>자료를 함께 보며 사실관계와 대응 순서를 정리합니다.</p></article><article><b>03</b><h3>비대면 상담</h3><p>멀리 있어도 전화·이메일로 자료를 주고받을 수 있습니다.</p></article></div><p className="priceNote">상담 및 사건 비용은 업무 범위와 자료를 확인한 뒤 사전에 안내합니다.</p></section>
<section className="cta"><div><p className="eyebrow">READY TO TALK</p><h2>무엇부터 설명할지 몰라도 괜찮습니다.</h2><p>{site.hours} · {site.tel}</p></div><Link className="btn primary" href="/contact">상담 준비 시작</Link></section></>}
