import type {Metadata} from 'next';
import Link from '../../components/SiteLink';
import {notFound} from 'next/navigation';
import {studio,pageInfo} from '../../data/studio';
import {asset,absolute} from '../../lib/urls';
import {ProjectGallery,BriefBuilder,MaterialStudy} from '../../components/StudioTools';
type Key=keyof typeof pageInfo;
export function generateStaticParams(){return Object.keys(pageInfo).map(page=>({page}));}
export async function generateMetadata({params}:{params:Promise<{page:string}>}):Promise<Metadata>{const {page}=await params;const info=pageInfo[page as Key];return info?{title:info[0],description:info[1],alternates:{canonical:absolute(`/${page}/`)}}:{};}
export default async function Page({params}:{params:Promise<{page:string}>}){const {page}=await params;if(!(page in pageInfo))notFound();const [title,text]=pageInfo[page as Key];return <><section className={`page-heading section ${page==='projects'?'portfolio-heading':''}`}><span className="eyebrow">FORME / 07 — {page.toUpperCase()}</span><h1>{title}</h1><p>{text}</p>{page==='projects'&&<p className="archive-note">FOUR CATEGORIES / EIGHT STORIES · 가상 공간 디자인 포트폴리오</p>}</section>{page==='projects'&&<section className="section"><ProjectGallery/></section>}{page==='services'&&<><section className="section service-details">{studio.services.map((s,i)=><article key={s.id}><span className="eyebrow">0{i+1} / {s.en}</span><h2>{s.name}</h2><p>{s.text}</p><ul>{s.items.map(t=><li key={t}>{t}</li>)}</ul><Link className="text-link" href="/contact/">이 공간의 상담 준비하기 ↗</Link></article>)}</section><MaterialStudy/></>}{page==='studio'&&<><section className="studio-photo"><img src={asset('living.webp')} srcSet={`${asset('living-small.webp')} 768w, ${asset('living.webp')} 1536w`} sizes="90vw" alt={studio.projects[0].subtitle} width="1536" height="1024"/></section><section className="section principle-grid">{studio.principles.map(([n,t,p])=><article key={n}><span>{n}</span><h2>{t}</h2><p>{p}</p></article>)}</section></>}{page==='process'&&<section className="section process-list">{studio.steps.map(([t,s,p],i)=><article key={t}><span>0{i+1}</span><div><h2>{t} — {s}</h2><p>{p}</p></div></article>)}<p className="small">실제 범위와 일정은 현장 확인 및 계약 조건에 따라 정합니다.</p><Link className="text-link" href="/contact/">첫 이야기 시작하기 ↗</Link></section>}{page==='contact'&&<section className="section"><BriefBuilder/><div className="contact-notes"><p>{studio.contact.hours}</p><p>{studio.contact.region}</p><p>가상 업체입니다. 전화번호·주소·문의 전송 기능은 제공하지 않습니다.</p></div></section>}{page==='privacy'&&<section className="section privacy"><h2>데모의 입력 정보</h2><p>상담 준비 도구는 이름·전화번호·이메일을 요청하지 않으며, 선택값을 서버에 전송하거나 저장하지 않습니다. 복사 버튼을 누르면 선택한 요약만 클립보드에 복사합니다.</p><h2>에디터 저장 정보</h2><p>에디터의 편집값은 이 브라우저의 해당 사이트 IndexedDB에 저장됩니다. 다른 사이트나 다른 방문자에게 적용되지 않습니다. 에디터 초기화로 해당 브라우저의 편집값을 삭제할 수 있습니다.</p><h2>이미지와 사례</h2><p>공간 이미지는 AI로 제작한 가상 디자인 이미지입니다. 프로젝트 이름, 면적, 설명은 포트폴리오 시연용 예시이며 실제 시공 실적이 아닙니다.</p></section>}</>}
